### ISSUE TITLE
Bug -- pulseaudio rules conflict with daemon.conf

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#104]
Pulseaudio.rules is a redunant rules file when pulse audio has it's own configuration file. Furthermore, it seems to conflict on my system causing an audible popping sound that can only be fixed by disabled the rules file.

/etc/pulse/daemon.conf
```
high-priority = yes
nice-level = -11
realtime-scheduling = yes
realtime-priority = 5
```

**Comment by Nefelim4ag** [comment]
While we have a rules with type LowLatency_RT, that not looks like good idea.
i.e. that type give more priority when pulseaudio have by default.

And that must be solved by some way.

**Comment by ryanmusante** [comment]
Should I use daemon.conf defaults?

**Comment by ryanmusante** [comment]
Which is preferred action in most cases?

    Use daemon.conf defaults and ananicy rules
    Use daemon.conf tweaked configuration and disable ananicy rules

**Comment by Nefelim4ag** [comment]
I prefer rearrange rules and types for that, to make default rule for pulse audio, match it in ananicy and have higher priority to others.

i.e. problem it self exists because ananicy generate many (may be too many?) things, which have same priority as pulse audio.

**Comment by ryanmusante** [comment]
I corrected pulseaudio problems with:
`options snd_hda_intel power_save=0 power_save_controller=N`

So, the conflict in settings with my pusleaudio configuration might not have as much to do with nice defaults.

**Comment by dim-geo** [comment]
I had occasional stutters with pulseaudio when using default ananicy rules. (no daemon.conf interference)
According to https://fitzcarraldoblog.wordpress.com/2017/04/20/stuttering-audio-in-linux-pulseaudio-strikes-again/, comments there and my testing, realtime scheduling of pulseaudio might cause stutters.

So, I changed pulseaudio rule like:
`{ "name": "pulseaudio", "type": "LowLatency_RT", "nice": -15 }`
So far in a couple of days testing no stutter appeared.

I removed the RT scheduling and decreased nice so that pulseaudio has higher priority than other "LowLatency_RT" processes.

**Comment by MR-Diamond** [comment]
> I removed the RT scheduling and decreased nice so that pulseaudio has higher priority than other "LowLatency_RT" processes.

So, which value did you gave to `nice` ? I ask because I also encountered stuttering with this rule and I'd prefer to adjust the rule instead of disable it :-)
