### ISSUE TITLE
[Feature Request] rule for nice inheritance

### ISSUE THREAD

**Issue by FlyingWombat** [Nefelim4ag/Ananicy#118]
A feature I believe is crucial to the usefulness of ananicy is a rule for setting the nice level that child processes inherit. 

Inheriting niceness and other attributes from a parent is useful in most cases.
But in the case of ananicy, doing so can sometimes break desired behavior.

For example: krunner
If you're using KDE, you probably use krunner all the time to launch various applications.
If there is a rule setting krunner's nice level to a non-standard value (like there is in the repo now), then every program started using krunner will be at krunner's nice value.
So, as it is, the user has to write a rule setting nice=0 for every normal program on their system, or remove the rule for krunner.
Steam running games, does the same thing: games end up at nice=19, if they don't have a rule of their own.
This goes for any program that launches other programs.

So, I propose the following:
* Add a property to rule definitions, name it "inheritance" or something, and have it's value be another rule (maybe disallow the "inheritance" property in that sub-rule, to avoid the possibility of rule recursion).
* An additional value for "inheritance" would be "System-Default". That would set every forked process to have the system default priority values.
* And of course, not using the inheritance rule, would keep the standard of forked processes inheriting their parent's priority values.

I wish I could be more help, but I'm a noob when it comes to OS stuff. And I haven't spent much time looking at ananicy's code. So, I have no idea how this would be implemented.

**Comment by RuRo** [comment]
Just found this, while trying to figure out, how to do exactly what OP asks.

I wanted to give my drop-down terminal and shell a very high priority so that even if the system is lagging due to some CPU intensive task, I could always drop into the shell. This doesn't work, of course, since for example giving my shell `-10` niceness will result in all the applications I run from the shell also inheriting this niceness, which completely defeats the purpose.

Am I supposed to explicitly list the priorities for all the executables, I might potentially run on the system?

I know, that this is how it works by default on Linux and I know, that there is no built-in mechanism for setting the niceness of children. However, please consider the fact that "`Linux has this behaviour for a reason`" is not a good excuse. Linux has many behaviours for various reasons and not all of them apply in all circumstances.

The Linux niceness priority system is on its own **not sufficient** for desktop users, which is why a tool like Ananicy exists in the first place. The security argument also does not apply here, since
1) The OP and I want to **lower** the priority of every child process (restricting the rule to only apply to the specified process, not its children)
2) If you use Ananicy, an attacker could just rename their executable, so that it matches some built-in rule (for example `linphon` gives you `-15` niceness and `realtime` ioclass)

The author of Ananicy doesn't owe us anything, of course. It's their project and they are free to implement whatever features they want, but I think closing this with "I don't think this is a good idea" without providing any alternative is not very *nice* (pun intended).

**Comment by FlyingWombat** [comment]
Maybe relevant: https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.7-clone3-new-cgroup

I have no idea how it would be used, though.
