### ISSUE TITLE
WarThunder profile (NAME=aces) might match other processes

### ISSUE THREAD

**Issue by Thermi** [Nefelim4ag/Ananicy#48]
I get a lot of logs for the nice value adjustment of "aces" processes, even when I don't play WT. I suspect the NAME value matches other processes but WT, too. I didn't catch any others, but the logs make it obvious. It'd be great if other persons with information about this could post it here and maybe we could find a solution, if it is a problem. I see the NICE value being changed from 19 to -5 and 0 to -5.

**Comment by Nefelim4ag** [comment]
You need to play with regex, afaik pgrep use regexes

On Dec 11, 2017 2:17 PM, "Thermi" <notifications@github.com> wrote:

I get a lot of logs for the nice value adjustment of "aces" processes, even
when I don't play WT. I suspect the NAME value matches other processes but
WT, too. I didn't catch any others, but the logs make it obvious. It'd be
great if other persons with information about this could post it here and
maybe we could find a solution, if it is a problem. I see the NICE value
being changed from 19 to -5 and 0 to -5.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Nefelim4ag/Ananicy/issues/48>, or mute the thread

**Comment by Thermi** [comment]
Okay, I figured out that at least `gcc` seems to be matched by this in some cases.

**Comment by Thermi** [comment]
Solved in #53
