### ISSUE TITLE
Upgrade of Ananicy replaces removed rules files

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#87]
What is the best option to prevent particular rules from being parsed at boot? ## Comment them out in the rules file? With each install, the files that I have deleted are automatically reinstalled to the location and added to the queue, if they are overwritten than they will lose the previous configuration.

**Comment by Nefelim4ag** [comment]
Add file like zzzoverwrite.rules
and just add copy rule names without props to that file.

i.e.:
NAME=ananicy TYPE=BG_CPUIO PGREP_ARGS="-xw" -> NAME=ananicy

Because Ananicy scan rules one by one and do overwriting like:
read rules string -> get NAME -> md5sum(NAME) -> write rule to <run_path>/md5sum(NAME).rules
